### ISSUE TITLE
Flex Layout

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [gildata/redux-seeds#12]
# Flex Layout

https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes

http://learnlayout.com/flexbox.html

https://css-tricks.com/snippets/css/a-guide-to-flexbox/

```css

.container{
    display: flex;
}

.item{
    flex: 1;
}


```
